### PR TITLE
Docs: mock servers

### PR DESCRIPTION
**Pull request by philsturgeon**

### CODE REVIEW

**Comment by philsturgeon** [comment]
@rowa97 hey, if this looks good enough to go into your branch can we merge it? can add images to them all later in the same effort.

**Comment by rowa97** [comment]
Edits: https://docs.google.com/document/d/1QLUbygFyaUlLjO1Wbfa8aFjiB95YEAQY7OIItMrzcnI/edit?usp=sharing

**Comment by philsturgeon** [comment]
@rowa97 awesome feedback, thank you! I know its a bit more fiddly sometimes but could we use the Suggestion button for any more feedback? It's easier to track than alt tabbing between things and double checking I copied and pasted bits right.

**Comment by philsturgeon** [comment]
Btw I implemented the stuff from the doc.

**Pull request merged**
